name: Shellcheck

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 1 * * *"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master